# Generated by Django 5.1.4 on 2025-01-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('SIMPLES', 'Simples'), ('DUPLO', 'Duplo'), ('LUXO', 'Luxo')], max_length=10)),
                ('capacity', models.IntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_availabe', models.BooleanField(default=True)),
            ],
        ),
    ]
