# Generated by Django 5.1.4 on 2025-01-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_availabe',
            new_name='is_available',
        ),
    ]
