# Generated by Django 5.1.4 on 2025-02-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_capacity_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SIMPLES', 'Individual (1)'), ('DUPLO', 'Duplo (2)'), ('TRIPLO', 'Triplo (3)'), ('QUADRUPLO', 'Quadruplo (4)'), ('QUINTUPLO', 'Quintuplo (5)'), ('SEXTUPLO', 'Sextuplo (6)')], max_length=10),
        ),
    ]
