# Generated by Django 5.1.4 on 2025-02-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='daily_rate',
        ),
        migrations.AddField(
            model_name='room',
            name='cooling_type',
            field=models.CharField(choices=[('AR_CONDICIONADO', 'Ar-condicionado'), ('VENTILADOR', 'Ventilador')], default=1, max_length=15),
        ),
    ]
