# Generated by Django 5.1.4 on 2025-01-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDENTE', 'Pendente'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
    ]
