# Generated by Django 5.1.4 on 2025-01-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryconsumption'),
        ('reservations', '0004_reservationextra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationextra',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='reservationextra',
            name='extra_detail',
        ),
        migrations.AddField(
            model_name='reservationextra',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='reservationextra',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservationextra',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='reservations.reservation'),
        ),
    ]
