# Generated by Django 5.1.4 on 2025-01-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_rename_price_reservationextra_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='extra_charges',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDENTE', 'Pendente'), ('CANCELADA', 'Cancelada')], default='PENDETE', max_length=10),
        ),
        migrations.DeleteModel(
            name='ReservationExtra',
        ),
    ]
