# Generated by Django 5.1.4 on 2025-01-12 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_inventoryconsumption'),
        ('reservations', '0009_inventoryitem_alter_reservationitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
