# Generated by Django 5.1.4 on 2025-01-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_inventoryconsumption'),
        ('reservations', '0012_alter_reservationitem_item_delete_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='consumed_items',
            field=models.ManyToManyField(through='reservations.ReservationItem', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_items', to='reservations.reservation'),
        ),
    ]
