# Generated by Django 5.1.4 on 2025-01-12 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_reservation_consumed_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='consumed_items',
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_items', to='reservations.reservation'),
        ),
    ]
