# Generated by Django 5.1.4 on 2025-02-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_remove_reservation_consumed_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
