# Generated by Django 5.1.4 on 2025-02-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_reservation_daily_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
