# Generated by Django 5.1.4 on 2025-01-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('reservations', '0003_reservation_extra_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.inventoryitem')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_consumptions', to='reservations.reservation')),
            ],
        ),
    ]
