# Generated by Django 5.1.4 on 2025-02-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_inventoryconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.inventoryitem')),
            ],
        ),
    ]
